# Generated by Django 2.2.1 on 2019-07-14 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandinfo',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 14, 22, 34, 36, 677719), null=True),
        ),
        migrations.AlterField(
            model_name='platforminfo',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 14, 22, 34, 36, 681458), null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 14, 22, 34, 36, 683276), null=True),
        ),
    ]
